import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import { Inter, Montserrat } from 'next/font/google'
import './globals.css'

const montserrat = Montserrat({
  subsets: ['latin'],
  weights: [400, 500, 600, 700],
  variable: '--font-montserrat'    
})

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable}`}> 
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
